// apps/web-app-svelte/src/lib/components/sliders/CastSlider.svelte
<script lang="ts">
	interface CastSliderProps {
		name: string;
		id: number;
		image: string | null;
		character: string;
	}

	export let cast: CastSliderProps[];
</script>

<div class="scrollbar-hide flex snap-x snap-mandatory flex-row gap-6 overflow-x-auto">
	{#if cast.length > 0}
		{#each cast as p}
			<a href={`/comrade/${p.id}`}>
				<div class="snap-start">
					<div class="flex flex-col gap-2">
						<div class="rounded-lg">
							<img
								src={p.image || '/PortraitPlaceholder.png'}
								width={160}
								height={240}
								class="rounded-lg"
								alt={`${p.name} pic`}
							/>
						</div>
						<div class="flex max-w-[160px] flex-col">
							<div class="truncate whitespace-nowrap" title={p.name}>{p.name}</div>
							<div class="text-sm text-gray-500" title={p.character}>{p.character}</div>
						</div>
					</div>
				</div>
			</a>
		{/each}
	{/if}
</div>

// apps/web-app/src/components/CastSlider.tsx
import PortraitPlaceholder from "@/public/PortraitPlaceholder.png";
import Image from "next/image";
import Link from "next/link";

export interface CastSliderProps {
  cast: { name: string; id: number; image: string | null; character: string }[];
}

const CastSlider = ({ cast }: CastSliderProps) => {
  return (
    <div className="scrollbar-hide flex snap-x snap-mandatory flex-row gap-6 overflow-x-auto">
      {cast.length > 0
        ? cast.map((p) => (
            <Link key={p.id} href={`/comrade/${p.id}`}>
              <a>
                <div className="snap-start">
                  <div className="flex flex-col gap-2">
                    <div className="rounded-lg">
                      <Image
                        src={p.image || PortraitPlaceholder}
                        width={160}
                        layout="fixed"
                        height={240}
                        className="rounded-lg"
                        alt={`${p.name} pic`}
                      />
                    </div>
                    <div className="flex max-w-[160px] flex-col">
                      <div className="truncate whitespace-nowrap" title={p.name}>{p.name}</div>
                      <div className="text-sm text-gray-500" title={p.character}>{p.character}</div>
                    </div>
                  </div>
                </div>
              </a>
            </Link>
          ))
        : "No reported cast for this movie :("}
    </div>
  );
};

export default CastSlider;
